version: '3.9'

services:
  backend-core:
    build: ./backend-core
    container_name: backend-core
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"

  ms-email-sender:
    build: ./ms-email-sender
    container_name: ms-email-sender
    ports:
      - "5001:5001"